FROM nginx:1.25.3
LABEL describe="render nginx"
COPY nginx-render.conf /etc/nginx/nginx.conf

# VOLUME nginx.conf /etc/nginx/nginx.conf
ENV NGINX_VERSION 1.25.3
EXPOSE 10000/tcp
EXPOSE 10000
# RUN nginx -t
# RUN ["/bin/bash","-c","echo hello world"]
CMD ["nginx", "-g", "daemon off;"]